### ISSUE TITLE
Handling of 'repos' JSON key is confusing

### ISSUE THREAD

**Issue by mbarnes** [projectatomic/rpm-ostree-toolbox#57]
This is probably low priority, but it stumped me for a good hour or two.

My understanding is the "repos" key in a JSON file lists yum repository names (the section names in a .repo file), but in the _copyexternals() method of TaskBase, it assumes each list item is the base name of a .repo file.

I was trying to use a .repo file that defined yum repositories for rhel-7 and rhel-7-debuginfo, and the treecompose command kept complaining about not being able to find these repositories.  Turns out it was because I had named the .repo file slightly differently than either of the repository names.

I was able to work around the problem once I read the code and figured out what it was expecting, but this may cause confusion for other users.

I guess to solve this, TaskBase would need to parse all the *.repo files and build a dictionary of { repo_name: repo_filename } entries, and then lookup each repository name from the JSON list to get the corresponding .repo filename?

**Comment by cgwalters** [comment]
The https://github.com/cgwalters/rpm-ostree/commits/libhif libhif branch gives a much more useful error message if a repository file isn't found.
