### ISSUE TITLE
If --ostree path exists, treecompose will fail

### ISSUE THREAD

**Issue by baude** [projectatomic/rpm-ostree-toolbox#59]
suppose --ostree-repo is /home/foo/bar/rawhide

If you happen to mkdir -p /home/foo/bar/rawhide prior to running treecompose, the treecompose will traceback.  We need to take the extra step to see if the dir is blank and go from there.

Ill clean this up.

**Comment by baude** [comment]
Here is an example.

[bbaude@localhost ~]$ mkdir -p /tmp/fedora/rawhide


[bbaude@localhost ~]$ sudo rpm-ostree-toolbox treecompose -c ~/docker/fedora-atomic/config.ini --ostree /tmp/fedora/rawhide/
('workdir', None)
('rpmostree_cache_dir', None)
('pkgdatadir', '/usr/share/rpm-ostree-toolbox')
('os_name', 'fedora-atomic')
('os_pretty_name', 'Fedora Atomic')
('tree_name', 'docker-host')
('tree_file', 'fedora-atomic-docker-host.json')
('arch', 'x86_64')
('release', 'rawhide')
('ref', 'fedora-atomic/rawhide/x86_64/docker-host')
('yum_baseurl', 'http://dl.fedoraproject.org/pub/fedora/linux//development/rawhide/x86_64/os/')
('lorax_additional_repos', None)
('is_final', None)
('lorax_exclude_packages', 'fedora-productimg-server, fedora-productimg-cloud, fedora-productimg-workstation')
('local_overrides', None)
('http_proxy', None)
('selinux', True)
('configdir', None)
('docker_os_name', 'fedora')
workdir=/tmp/atomic-treecomposeb5ozrJ.tmp
rpmostree_cache_dir=None
pkgdatadir=/usr/share/rpm-ostree-toolbox
os_name=fedora-atomic
os_pretty_name=Fedora Atomic
tree_name=docker-host
tree_file=/home/bbaude/docker/fedora-atomic/fedora-atomic-docker-host.json
arch=x86_64
release=rawhide
ref=fedora-atomic/rawhide/x86_64/docker-host
yum_baseurl=http://dl.fedoraproject.org/pub/fedora/linux//development/rawhide/x86_64/os/
lorax_additional_repos=None
is_final=None
lorax_exclude_packages=fedora-productimg-server, fedora-productimg-cloud, fedora-productimg-workstation
local_overrides=None
http_proxy=None
selinux=True
configdir=/home/bbaude/docker/fedora-atomic
docker_os_name=fedora
Traceback (most recent call last):
  File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose-main", line 72, in <module>
    main()
  File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose-main", line 60, in main
    treecompose.main(cmd)
  File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose/treecompose.py", line 155, in main
    origrev, newrev = composer.compose_tree()
  File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose/treecompose.py", line 50, in compose_tree
    _,origrev = self.repo.resolve_rev(self.ref, True)
  File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose/taskbase.py", line 298, in repo
    self._repo.open(None)
GLib.Error: g-io-error-quark: Reading objects/ directory: open: No such file or directory (1)

**Comment by cgwalters** [comment]
Maybe the fix is to clarify the ostree error message to say something like `...No such file or directory; repository not initialized?`

Or we could just auto-initialize I guess, but I'm considering at some point having another repository mode.

**Comment by baude** [comment]
Ok proposal will be as follows:

If the -o output dir for treecompose EXISTS but is not INITIALIZED, we will fail_msg to telling the user to initialize the repo with ostree --repo=/path/to/repodir init --mode=archive-z2
