### ISSUE TITLE
create-vm-disk is broken

### ISSUE THREAD

**Issue by copumpkin** [projectatomic/rpm-ostree-toolbox#86]
I know it's deprecated, but blog posts still reference it, and it fails when I try to run it as follows:

```
Failed to open file '/usr/share/rpm-ostree-toolbox/js/main.js': No such file or directory
```

Since the `src/js` folder was deleted a few months ago.

**Comment by bssrikanth** [comment]
I am also facing same issue where building atomic image using fedora24. Please let me know if there is a solution/workaround for it

**Comment by bssrikanth** [comment]
Is there any alternative way of create vm disk? since js folder is deleted.. please let us know.

**Comment by cgwalters** [comment]
We expect people to use imagefactory (which uses anaconda) now.
